// <auto-generated />
using System;
using Konyvtar_katalogus.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Konyvtar_katalogus.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    partial class LibraryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Konyvtar_katalogus.Models.Book", b =>
                {
                    b.Property<int>("bookid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("isbn")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("bookid");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Konyvtar_katalogus.Models.Copy", b =>
                {
                    b.Property<int>("copyid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InventoryNumber")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<bool>("isAvailable")
                        .HasColumnType("INTEGER");

                    b.HasKey("copyid");

                    b.HasIndex("BookId");

                    b.ToTable("Copies");
                });

            modelBuilder.Entity("Konyvtar_katalogus.Models.Fine", b =>
                {
                    b.Property<int>("fineid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoanId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("amount")
                        .HasColumnType("TEXT");

                    b.Property<bool>("isPaid")
                        .HasColumnType("INTEGER");

                    b.HasKey("fineid");

                    b.HasIndex("LoanId");

                    b.ToTable("Fines");
                });

            modelBuilder.Entity("Konyvtar_katalogus.Models.Loan", b =>
                {
                    b.Property<int>("loanid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReaderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("copyid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("loanDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("returnDate")
                        .HasColumnType("TEXT");

                    b.HasKey("loanid");

                    b.HasIndex("ReaderId");

                    b.HasIndex("copyid");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("Konyvtar_katalogus.Models.Reader", b =>
                {
                    b.Property<int>("readerid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("readerid");

                    b.ToTable("Readers");
                });

            modelBuilder.Entity("Konyvtar_katalogus.Models.Copy", b =>
                {
                    b.HasOne("Konyvtar_katalogus.Models.Book", "Book")
                        .WithMany("Copies")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Konyvtar_katalogus.Models.Fine", b =>
                {
                    b.HasOne("Konyvtar_katalogus.Models.Loan", "Loan")
                        .WithMany()
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("Konyvtar_katalogus.Models.Loan", b =>
                {
                    b.HasOne("Konyvtar_katalogus.Models.Reader", "Reader")
                        .WithMany("Loans")
                        .HasForeignKey("ReaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Konyvtar_katalogus.Models.Copy", "Copy")
                        .WithMany("Loans")
                        .HasForeignKey("copyid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Copy");

                    b.Navigation("Reader");
                });

            modelBuilder.Entity("Konyvtar_katalogus.Models.Book", b =>
                {
                    b.Navigation("Copies");
                });

            modelBuilder.Entity("Konyvtar_katalogus.Models.Copy", b =>
                {
                    b.Navigation("Loans");
                });

            modelBuilder.Entity("Konyvtar_katalogus.Models.Reader", b =>
                {
                    b.Navigation("Loans");
                });
#pragma warning restore 612, 618
        }
    }
}
